apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: ExternalName
  externalName: postgres.tail5b1a8.ts.net
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP