apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-ui-config
data:
  config.yml: |
    # Listen interface.
    listen_addr: 0.0.0.0:8000

    # Base path of Registry UI.
    uri_base_path: /

    # Background tasks.
    performance:
      # Catalog list page size. It depends from the underlying storage performance.
      catalog_page_size: 100

      # Catalog (repo list) refresh interval in minutes.
      # If set to 0 it will never refresh but will run once initially.
      catalog_refresh_interval: 60

      # Tags refresh interval in minutes (background job that caches all tags).
      # If set to 0, background refresh is disabled and tags will always be
      # refreshed online when browsing (ignoring tags_online_refresh_max_count).
      tags_async_refresh_interval: 360

      # Max tags per repo to allow refreshing tags online when browsing.
      # If repo has fewer tags than this limit, tags will be fetched fresh on page load.
      # If repo has more tags, it will use cached tags from background job.
      # Set to 0 to always use cache (no online refresh).
      # Note: This setting is ignored when tags_async_refresh_interval=0 so you can ever browse tags.
      tags_online_refresh_max_count: 1000

    # Registry endpoint and authentication.
    registry:
      # Registry hostname (without protocol but may include port).
      hostname: bucciarati.tail5b1a8.ts.net
      # Allow to access non-https enabled registry.
      insecure: false

    # UI access management.
    access_control:
      # Whether users can the event log. Otherwise, only admins listed below.
      anyone_can_view_events: true
      # Whether users can delete tags. Otherwise, only admins listed below.
      anyone_can_delete_tags: false
      # The list of users to do everything.
      # User identifier should be set via X-WEBAUTH-USER header from your proxy
      # because registry UI itself does not employ any auth.
      admins: []

    # # Options for tag purging.
    # purge_tags:
    #   # How many days to keep tags but also keep the minimal count provided no matter how old.
    #   keep_days: 90
    #   keep_count: 10

    #   # Keep tags matching regexp no matter how old, e.g. '^latest$'
    #   # Empty string disables this feature.
    #   keep_regexp: ''

    #   # Keep tags listed in the file no matter how old.
    #   # File format is JSON: {"repo1": ["tag1", "tag2"], "repoX": ["tagX"]}
    #   # Empty string disables this feature.
    #   keep_from_file: ''
