apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-ui-config
data:
  config.yml: |
    # Listen interface.
    listen_addr: 0.0.0.0:8000

    # Base path of Registry UI.
    uri_base_path: /

    # Registry endpoint and authentication.
    registry:
      # Registry hostname (without protocol but may include port).
      hostname: bucciarati.tail5b1a8.ts.net
      # Allow to access non-https enabled registry.
      insecure: false
