---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-psql
  namespace: o11y
spec:
  encryptedData:
    password: AgC3X0Zf60Z/b0ndPm04+IlCTszvH4V+aPiGjPYhQOvgOWx3vkPuclMHKvSyxt0hjQfzFeGZfVSDl0onaUQpIXiltWAK3+8+LMB7fyCqavk53nyCIR+ZtTtyw174xcJxw5SYsRhZNwDOvBO67OU0hXD/LLFhFAb2dsw6p8bwPFAoQFxs0u9zHYlFq6mGu6Dm/jYg9LikjsYqMIaMdvmxhx7+PjbnraN6DlMnSSP3qvaiGrVu7OH72SEjFyDcLKdvNx+An7jVCqh12VtrK/71FXTvNHm0qLaeJnQ+FwtPkuNJH58K6lR1k8sSsJF1mzVG0SGRu9TluEbBS4Oi3dT3mwX/59X7ZlSkyPvuc2qM9H0qomyV202UdbqJAj8BDfRNVoCnzFTSMvT9aVYRxI99C0pd7TTPQ/+dWBiSOcpI8aZTCr37GSsO3th7BVonF4qB/4MrXcNjRwvLGLt5It1+0SuZH3yyTmlzmSeSa5aUXOqjpUGqLrn3vnvz0HrunKoFqkcthW5npal/AyEcYq6uwDmDF9XqtPVg0lPnOYnKaJ6i7xHu3sdeIQfibEkrU2ZDoXQyr+5EVj8VU76doRhgn7SWz2UQbVMzk6XpmB0dMdEBqVXOfhLLh6wRrS3nKBr7HozEIO95R2YBgVTp6pfWNMuOuCjeMqdWAJVyy+5ZOaZ/ZARYOqJpZ58fyU/u4/25+91oCxdAiWP/eIDNtADN
  template:
    metadata:
      name: grafana-psql
      namespace: o11y
