apiVersion: v1
kind: Namespace
metadata:
  name: infisical
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical
  namespace: default
spec:
  encryptedData:
    client_id: AgC2M89+1re21pS5EaHE0LRp6U2oMgm3SHxKQIvplhufrU8mPPnfvYs33UocN5bmjrJ4I41syARB9LA8CUUNUtcqpwZZIQ8wxNp1z7Ta8wx8mceDTSlXmXRtP4mnnbX11jR8yRwd4ViWxzpZNx9uwFjr86e0F2j5BXxFVpHLJ/pDIDhO7T5Y2B/mHPdSQXv8l4vOvruK26XhWt1OZtnUauFCVorzcytiaruT3KvKSZbw6IhhcU+XsikOvjF3Fp+ZS2jkdjIVV0qzRI9dd+RKOwDde45am+8+Wv3Rl5iq9KBAWCXqdmF77gQ5fEN/Ovxy1pF1zVgElo7SK6XLWLpy6hPL2zitbvfh0hEPg7ziSnrYE3ZaUQw60TvzrGkwuCELINmT/8xiR9usRNXrgznCo3Fx1y09KfDtkUbmaqaAIcHYx9L5RWedIqggQfMw5I+kYFVEyKY60GUGrygx5zNc4yAec8Dk3QKOh0a+QdcT8QgVW+Xi9TA7dDJFqkPX3xYa5pL8vpaiB9CLSLGEI8R12/OGLbYy1iDZ70rVsSiRhMdBwrVApy54gbx/n/tzs1ysadV6IsVlUeI7MxwUxSDOHTk+rquvkGcKz1qAPIZr1ni0cIjusmFcLSmiBax0pHK07Nwdmo4SodO2/ughgih0NhPtV12PLv+9x+mwqy2HboWaT36BjrZIbGIsDwSqgJ6kjye9Y+mClXAD2lt/wse4UY38ELwwIppv5PSb96g68AXQqrFkUNk=
    client_secret: AgCTVVHH/GoFv7wTzZqxmrE+CKdXpP8KAUZH52ydveVo0GgwHmbmD1wKJhgKBxyVSWtTgc1vY7JWS0SioUNFULwdAQnCKRx3dOSgCxv24opvSc1xQ2y4wChPE7pcRelqxsvaSxRqR66rIvYpVnjGZXni7vt7bm47SYrpSMsSPOllLqUefS99Gmwyz1ckrR2chsBlIoPUA3FBKjWrZKlElIpV/aQekloOGtpJ3kAKGguLYB8IVBHjeiFWTIn9mo4vgxLtdbrOBKf9kUx1nZrzgbUkDffTRwFOQpMOxC25bk41IwRC3H4LqqUiAiWHQ+p2vNnhHq4yPmMcuXw6nn76PfovfJ/ya7/SlSdLUrFkFRU6qKHp1jeJeKn65eOn2oPPXN9fmCp8eCCwYDnVNtJO0i+/zfpgT6hqhtazG4S5sbNq7foJI5BhIZ4KJenvAbdEnLRC31qn6ZnGW8YfdIw8ZTOGQfEkONRmxVFpipSsQIpcArCQl4PqiDVWvuXdV+gqsr1/HNYJ8q9kGu7LAQahU76HnZyQAxqJuJYvlRv2LmfiYH/9XkhRa6xeCcWFJgwVSQpmDKaT0P3FQdQUrqXWyKRf1YqfwklMg73Zb00hzbxxcGDL356romjukQItO+NzvM5oT573irjCmA852fF6LZE4QiUUg9E8/W28spr7y8taLYZkmoJFFDFOrL8Q/u4YJqeSqVPFoy4Tmm12mjxDPk6UX//HbVVhRk484q+bJ9pvz6VNvMRs16KPnWZYB8skGikdLrlyJ7le0uBTGNJozwq/
  template:
    metadata:
      name: infisical
      namespace: default
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://diavolo.tail5b1a8.ts.net
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            key: client_id
          clientSecret:
            name: infisical
            key: client_secret
      secretsScope:
        projectSlug: cluster
        environmentSlug: dev