apiVersion: v1
kind: Namespace
metadata:
  name: infisical
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical
  namespace: infisical
spec:
  encryptedData:
    client_id: AgBkjfvi0sJ7klcL4u7SI6h7a9Dx0jsgtk5f53j447Be6Jk4oLtU/8b7RlpAihb7ayBCMQuVrnVrLQXI4e2751+v03jmlZbdLRYqWsEgoJqeBMj/jlP2w1HD3F38uwBxOVWUUShdCAUiD7eTH7yS/RXf6guUZ7UlnLzFM6e0a9amO3uYCowMkffIsGwjRCyHcrRoUbFyMcrNGJ8DYtB/XmsgFRbzGPOJ/stEQSlWEyvO7DJHmuYbr0wOG/xbplq7NQp+w6m/aIMFaS9tCx8LzcOp2aqV/gIHEO2bqYUV6b7JenCONgy2UJCw/QOKhwu2ww/sHdvsYYHazR7NEp+xbOVwkArO6pp0iKyBx7Rrhk1p16hz9VScAGwSKFUGqlLNTfu/j9F06QGq/nSWbLswYY+L7a1N2YsJoSYpNk+DKPWt+KaRkxQISOLP5NBiPtI9bnoU16jnIiJA/BIXXXwQbD82A0J+DBl07WkyjIwSGnBxh8h1YTXV6C6P+jFleKLBtKHvUYjEZdnnhG4xDG361Miw/O208VcsWNK2eBx7oO9OY8oK2NdtoAbTGvQdlflOZy27ZubRUV/LP9UaYSx2SDdIiEoArJVEEMicKIHeuEDlOJOF5GsorUoeIIv02VpRpN1gtA9tJBefcrb+t2T3dd+z7Ez04u+qIcVngE8Xe0j2TMuVx0Kd3llJkBArvUOGrY7h0wBS6LnEUHCFALxqLUQAtrivFokkeV6EhNhqR/z+IyC7AOo=
    client_secret: AgB5Xb0c3tyWOFmg+RUEpC2hoZXymL7DtuVWss177IIZfVbmp3BZrFF/vRTmvxADSiJg2kKiySkLJkUhi9lrMy0XmAzoyE12Y7+rwtB8ejOV+bu3N+pkfNpeMxB6irKqhfBKijgJC4EyRFtdZgSnQn91e8C94dNqZ/TJ9gc4iXFnz5X+ULG+cOa1D4eprn4QCn1jA2EEc75Kpm/yRQPQVTWqU6+OQwaJgKAcE16VNv++T5nk0TFTGQ/bfXBafaBMKbvOH/QSFMBK3GnPHLsa8PWtXU386JmfuHlnBuNlJpWh2qFni4ZRZkw58Zbp1659dtRsqh3mz2ccEkjkwTXQ0bqf2E4kuzc8rPyWgmLbn2stANa1oYgXbXHOsIQhM+ngXz2gWKxdr3znHYm38ZFL3NzqD9Pc9+8LM89neFRrbIa7GdAHcY1KtmHJ9bzVVPqToiu6XDcSktZ1J/pN1AxLmhlmH5Vg7GTtgAyzgufyMUkOwRlJkz85BlVrGZtSSQunavGUkgR24IuHzMeK7pbMpRvvsAOA3bnaSQenEaDkJkHaoZBYs1cZfZHctpkqH/rI2kHO6KBRSMJ6DNpfSbuNR3PGbi0F+gy4l1JKx3XmKNLr0t1/A+LCtWPUUZfGgNMZOmk1VJ/wPuDshk1eoTqerGwsfryq1cLLhEtUwEBRhFD/zNjhBhm21VcJr1j45B6KH3NcxxKLkwaAHiagQjWNGUgxAYbNmQ+Z6GOUaVV7oLWkBdEuPSfvBIbpefE0Qb+1O5z+D0DXDVaZkpQxWqHZmxuG
  template:
    metadata:
      name: infisical
      namespace: infisical
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-dev
  namespace: infisical
spec:
  provider:
    infisical:
      hostAPI: https://diavolo.tail5b1a8.ts.net
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            key: client_id
            namespace: infisical
          clientSecret:
            name: infisical
            key: client_secret
            namespace: infisical
      secretsScope:
        projectSlug: cluster
        environmentSlug: dev
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-prod
  namespace: infisical
spec:
  provider:
    infisical:
      hostAPI: https://diavolo.tail5b1a8.ts.net
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            key: client_id
            namespace: infisical
          clientSecret:
            name: infisical
            key: client_secret
            namespace: infisical
      secretsScope:
        projectSlug: cluster
        environmentSlug: prod