apiVersion: v1
kind: Namespace
metadata:
  name: infisical
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical
  namespace: infisical
spec:
  encryptedData:
    client_id: AgB7imfdgvQE61U2/DR4sFW2vd/xduMi3YTxvUtdRQmIKtXwSu4ex4BBcPqvqVdevkF6sUoERXWBiY8UWpP8g4DAOQQu4yAZOkORWnyPc1m+Spevg2PJKDjBQ81ZtgZH4sPlZwc+HcniUW13wxkKCvG5nFdG3YL+jJrqFd6jYkccBS8AgiAbOBMy5zc5QdMp3uI38udUmgLNk7hBH5qxkGWehIRQ+dKdB8tOmODt2lr9vpjyEyuGzdOer0fORwlHNrdx50ThhqtkhORwCvkbhDcbxNtbGmQu8SvLRj0/NKM+LwcFy5pDWcCEcyX0H+nIb9QlZ7Y0HvIdraB4CxVsOM3QIeYc7lZsUBv00rhf8WqXCnDO/S7hVtZ4vI9qPRfFRwqRBu+5OIVjXPU5+RQD+QrDTs9ihcB01YLbk6myxjKTHwsanhWsrNYBvOq4THsv6rHj2MOe+jNuraMwSiapXpxJ8myjFBL0Ochui3XCZjIwEYdgDX5hGvgil5ZK0Ekt9PaZQa7ACBDMShCyijQd9JL+j8W+9fCo+aDAS6fQgUg5fBOkMKjQtUzZK86/gXTYDjk9dXjLmdtAKf/2jj2C2kS3f5bj/w0SNH4IX5AzKPH6KZH0KEoxQwhK/+HstKQeO9pl+kL+nJqd5CoQNwZcNeleoHJAKcV87LVkaDaw+j0VIMWwJl2C/p8dFLi83sIorbAIBy+Za7CbaxHd7PYoQaMNRbrGDiaxKlYxJ7aUhthXm4qnuFI=
    client_secret: AgCNjiNQjN9gjUSCErEduoPJ2pRt/A81+6zmh6CNP+RSG9k7gaDi+GygamD5P9K6JTtevdP99BrhiPzBJ1cJwqXjmusf3R2UqnCvccg48n3Iy6Lpwl/y2W0bbkJ7L16LrH9l1BqBqLnvZgf7zliSvuZqldYCPE9Bezl+SUBcw+xp+OLvNhwb5WZ8o2EQOy42bk2qyvSXIZNa+Hop2DUS4Tmv56gzVENiZMaBCaJ3GlmyjAc8EneF3sXYbB3KcTVBiDP2AglydqNUiKiaBBLK7roncSKYgHYjfJM5lUGb6+mml8tGBDkm7j0+x15rRYSwSN7tMEQ33x3k03QAr9WYpc8cXUJxJzTFnlMIDUMQ27++RnXIYMrPm/9Ile60zKETcveGCTYgLzSbUMjy9E4btVzPx1f0LX4t52e3lAHdSX5ePASNhmp1LncVXFkdgUSbS5z8wEI0VafGeiQQrzB2Bzzh3DGLBfw2+bpdJc8dMlcBr7KZcog2hU4+tgIGEkbCQfwph7HzAF2SwxMIY6h6Ym22PSUScVAGD5F810ZJhpymei5nN0e81LmTomNs1wbh5BjWIUFPBCBmA1e4krrz1+Mn5RAWekQlrky0OxaHB9xGYrkWDfGQLpHFKAhnNUkW/2h2JxiUcqzRrseBbGDdFYZhvIHUTdhMffuhQLyBeXQuqKFzG66TMxX91LElSDnMeIwVnv4xL0U8WrT/N4SNrhVkOoW6QDgqHom31FSV63bkSUHwCGhSu3pW9uguv1W8Y2LPJyCEZejU5B7PlEhQ47Mq
  template:
    metadata:
      name: infisical
      namespace: infisical
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-dev
  namespace: infisical
spec:
  provider:
    infisical:
      hostAPI: https://diavolo.tail5b1a8.ts.net
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            key: client_id
            namespace: infisical
          clientSecret:
            name: infisical
            key: client_secret
            namespace: infisical
      secretsScope:
        projectSlug: cluster
        environmentSlug: dev
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-prod
  namespace: infisical
spec:
  provider:
    infisical:
      hostAPI: https://diavolo.tail5b1a8.ts.net
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            key: client_id
            namespace: infisical
          clientSecret:
            name: infisical
            key: client_secret
            namespace: infisical
      secretsScope:
        projectSlug: cluster
        environmentSlug: prod