apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ts-exporter-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: ts-keys

  data:
    - secretKey: ts-access-key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: ts-access-key
        metadataPolicy: None	
        nullBytePolicy: Ignore
    - secretKey: ts-net-id
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: ts-net-id
        metadataPolicy: None	
        nullBytePolicy: Ignore