apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ts-exporter
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - namespace: ts-exporter-dev
        url: https://1.2.3.4
      - namespace: ts-exporter-prod
        url: https://1.2.3.4

  template:
    metadata:
      name: '{{.namespace}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/moodyRahman/k8s-monorepo
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: guestbook
