apiVersion: v1
kind: Namespace
metadata:
  name: ts-exporter
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ts-exporter-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: ts-keys

  data:
    - secretKey: ts-access-key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: ts-access-key
        metadataPolicy: None	
        nullBytePolicy: Ignore
    - secretKey: ts-net-id
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: ts-net-id
        metadataPolicy: None	
        nullBytePolicy: Ignore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-exporter
spec:
  selector:
    matchLabels:
      app: ts-exporter
  template:
    metadata:
      labels:
        app: ts-exporter
    spec:
      containers:
      - name: ts-exporter
        image: bucciarati.tail5b1a8.ts.net/ts-exporter:main
        env:
          - name: TS_ACCESSKEY
            valueFrom: 
              secretKeyRef:
                name: ts-keys
                key: ts-access-key
          - name: TS_NET
            valueFrom: 
              secretKeyRef:
                name: ts-keys
                key: ts-net-id
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
